// Add new lessons here by mapping a slug to its .md filename (inside /public/content/teachings/)
// No need to touch any component — just add a new .md file and register it here.
const lessonSlugs: Record<string, string> = {
  'quran-author-misunderstanding': 'quran-author-misunderstanding.md',
  'trinity': 'trinity.md',
  'yesus-waaqa-dubbateera': 'yesus-waaqa-dubbateera.md',
  'ani-waaqayyodha': 'ani-waaqayyodha.md',
  'islaamummaa-fannifamuu': 'islaamummaa-fannifamuu.md',
  'kaliimatullaah': 'kaliimatullaah.md',
  'ruhuullaah': 'ruhuullaah.md',
  'waaqayyo-yesusin-dhile': 'waaqayyo-yesusin-dhile.md',
  'balballi-jannataa': 'balballi-jannataa.md',
  'maaliif-kristaanummaa': 'maaliif-kristaanummaa.md',
  'macaafni-sagalee': 'macaafni-sagalee.md',
  'deebilee-amansiisoo': 'deebilee-amansiisoo.md',
  'macaafa-kitaaba': 'macaafa-kitaaba.md',
  'rakkina-islaamummaa': 'rakkina-islaamummaa.md',
  'tawuraatii-injiliin': 'tawuraatii-injiliin.md',
  'nabiyyummaa-12': 'nabiyyummaa-12.md',
  'wangeelli-barnaabaas': 'wangeelli-barnaabaas.md',
  'muhammadii-phaawulos': 'muhammadii-phaawulos.md',
  'musee-muhammad': 'musee-muhammad.md',
  'muhammad-ergamaa': 'muhammad-ergamaa.md',
  'sheeyxana-funyaan': 'sheeyxana-funyaan.md',
  'haalli-duaatii': 'haalli-duaatii.md',
  'qamaleen': 'qamaleen.md',
  'quraanni-eeggameeraa': 'quraanni-eeggameeraa.md',
  'miidhaginni': 'miidhaginni.md',
  'keyyatoota-213': 'keyyatoota-213.md',
  'dogoggoroota-seenaa': 'dogoggoroota-seenaa.md',
  'haalli-quraana-haafsi': 'haalli-quraana-haafsi.md',
  'moggaasa-boqonnaawwan': 'moggaasa-boqonnaawwan.md',
  'jechoota-walfaallessan': 'jechoota-walfaallessan.md',
  'dubartootaa-quraana': 'dubartootaa-quraana.md',
  'ragaa-dubartootaa': 'ragaa-dubartootaa.md',
  'ayishaa': 'ayishaa.md',
  'dubartii-gurraattii': 'dubartii-gurraattii.md',
  'islaamummaa-nagayaa': 'islaamummaa-nagayaa.md',
  'isis': 'isis.md',
  'wahaabiizimii': 'wahaabiizimii.md',
  'muhammad-yihuudota': 'muhammad-yihuudota.md',
  'waadaa-zimmaa': 'waadaa-zimmaa.md',
  'giddu-gala-kiristiyaanaa': 'giddu-gala-kiristiyaanaa.md',
  'jihaadota-fashalaan': 'jihaadota-fashalaan.md',
  'jihaad-haarawa': 'jihaad-haarawa.md',
  'hayyoota-shororkeesummaa': 'hayyoota-shororkeesummaa.md',
  'bara-1979': 'bara-1979.md',
  'al-najaashii': 'al-najaashii.md',
  'ahimad-bitaatticha': 'ahimad-bitaatticha.md',
  'jihaad-itiyoophiyaa': 'jihaad-itiyoophiyaa.md',
  'summii': 'summii.md',
  'dogoggorawwan-kuma': 'dogoggorawwan-kuma.md',
  'soba-ahimad': 'soba-ahimad.md',
  'kaabaa': 'kaabaa.md',
  'son-of-god': 'son-of-god.md',
  'dhuga-baumsa': 'dhuga-baumsa.md',
};

export default lessonSlugs;
